name: SPA MM Finder
atlas:
  acquisition:
      - setAtlasOptics
      - setAperturesForLowMag
      - resetStage
      - removeSlit
      - atlas
  targets:
    finders:
      - AI square finder
    selectors:
      - Size selector
square:
  acquisition:
    - setAperturesForLowMag
    - moveStageWithAtlasToSearchOffset
    - realignToSquare
    - eucentricSearch
    - square
  targets:
    finders:
      - AI hole finder
      - Regular pattern
    selectors:
      - Graylevel selector
      - Distance from center selector
mediumMag:
  acquisition:
    - setAperturesForHighMag
    - setFocusPosition
    - tiltToAngle
    - moveStage
    - mediumMagHole
    - autoFocusAfterDistance
    - waitDrift
  targets:
    finders:
      - Medium Mag AI hole finder
highMag:
  acquisition:
    - highMag
